import React,{useMemo,useState} from 'react';
import {EvidenceChart,DataComponent,DataTable,Dropdown,Section,SortableItem,SortableRegion,useDataApp,useDashboardTabs} from '../../data-app-public.jsx';
import {metricNames,monthNames,formatNumber,formatCompact,formatMonth,shiftMonth,commonMonths,delta,summarize,sumComplete,seriesRows,annualRows,exportCsv} from './airport-data.js';
import './airport.css';
const tabs=[{id:'dashboard',label:'Comparativa'},{id:'season',label:'Estacionalidad'},{id:'detail',label:'Detalle por aeropuerto'},{id:'sources',label:'Fuentes y cobertura'}];
const countriesES=new Intl.DisplayNames(['es'],{type:'region'});
const topWithRest=(rows,key,n=12)=>rows.length<=n?rows:[...rows.slice(0,n),{[key]:'Otros ('+(rows.length-n)+')',Pasajeros:rows.slice(n).reduce((a,r)=>a+r.Pasajeros,0)}];
const stamp=x=>new Date(x).toLocaleString('es-ES',{timeZone:'Europe/Madrid',dateStyle:'medium',timeStyle:'short'});
function Select({label,value,choices,onChange,labels}){return <Dropdown label={label} showLabel value={value} choices={choices} onChange={onChange} formatChoice={v=>labels?.[v]??v}/>;}
function Plot({id,title,rows,sourceRows,queryId='traffic',type='line',x='Mes',y,series,height=300,...props}){return <EvidenceChart id={id} queryId={queryId} title={title} variant="card" rows={rows} sourceRows={sourceRows??rows} spec={{type,x,y,series,stackable:false,startAtZero:true,showXAxisLabel:false,showYAxisLabel:false,valueDecimals:y?.includes('%')?1:0}} height={height} {...props}/>;}
function Download({rows,name='observatorio.csv'}){return <button className="av-action" onClick={()=>exportCsv(rows,name)} disabled={!rows.length}>Descargar CSV ↓</button>;}
function Empty({children}){return <p className="av-empty">{children}</p>;}
export function DashboardContent(){
 const {queries,snapshot}=useDataApp(),{activeTabId}=useDashboardTabs(tabs),tab=activeTabId??'dashboard';
 const traffic=queries.traffic.rows,airports=snapshot.airports,all=airports.map(a=>a.code),name=c=>airports.find(a=>a.code===c)?.name??c,label=c=>`${name(c)} · ${c}`;
 const latest=traffic.map(r=>r.month).sort().at(-1);
 const [selected,setSelected]=useState(all),[metric,setMetric]=useState('passengers'),[chosenMonth,setChosenMonth]=useState('latest'),[window,setWindow]=useState('12'),[indexed,setIndexed]=useState(false),[year,setYear]=useState(String(Number(latest.slice(0,4))-1)),[detail,setDetail]=useState('AGP');
 const covered=useMemo(()=>commonMonths(traffic,selected),[traffic,selected]);const end=chosenMonth==='latest'?covered.at(-1):covered.includes(chosenMonth)?chosenMonth:covered.at(-1),start=end?(window==='all'?covered[0]:shiftMonth(end,1-Number(window))):null;
 const scope=end?traffic.filter(r=>selected.includes(r.airport)&&r.month>=start&&r.month<=end):[],compare=end?traffic.filter(r=>selected.includes(r.airport)&&[end,shiftMonth(end,-12)].includes(r.month)):[];
 const ranking=(end?summarize(traffic,selected,end,metric):[]).map(r=>({Aeropuerto:label(r.airport),[metricNames[metric]]:r.value,'Variación interanual (%)':r.change})).sort((a,b)=>(b[metricNames[metric]]??-1)-(a[metricNames[metric]]??-1));
 const trend=end?seriesRows(traffic,selected,start,end,metric,indexed,label):[],current=end?sumComplete(traffic,selected,end,metric):null,prev=end?sumComplete(traffic,selected,shiftMonth(end,-12),metric):null;
 const reset=()=>{setSelected(all);setMetric('passengers');setChosenMonth('latest');setWindow('12');setIndexed(false);};
 return <div className="av-page">
 <div className="av-context"><span>Andalucía · Gibraltar · Madrid · Barcelona</span><span>Comprobado {stamp(snapshot.refresh?.checkedAt??snapshot.generatedAt)}</span></div>
 {(tab==='dashboard'||tab==='season')&&<><div className="av-scope"><div className="av-scope-heading"><strong>Aeropuertos a comparar</strong><div className="av-presets"><button onClick={()=>setSelected(all)}>Todos</button><button onClick={()=>setSelected(airports.filter(a=>a.group==='Andalucía').map(a=>a.code))}>Andalucía</button><button onClick={()=>setSelected(['AGP','GIB'])}>Málaga y Gibraltar</button><button onClick={reset}>Restablecer</button></div></div><div className="av-airports">{airports.map(a=><button key={a.code} className={'av-airport '+(selected.includes(a.code)?'is-selected':'')} aria-pressed={selected.includes(a.code)} onClick={()=>setSelected(s=>s.includes(a.code)?s.filter(x=>x!==a.code):all.filter(x=>s.includes(x)||x===a.code))}><b>{a.code}</b><span>{a.name}</span></button>)}</div></div>
 <div className="av-controls"><Select label="Indicador" value={metric} choices={Object.keys(metricNames)} labels={metricNames} onChange={setMetric}/>{tab==='dashboard'?<><Select label="Mes de referencia" value={chosenMonth} choices={['latest',...covered.slice().reverse()]} labels={Object.fromEntries([['latest','Último mes común'],...covered.map(m=>[m,formatMonth(m)])])} onChange={setChosenMonth}/><Select label="Histórico" value={window} choices={['12','24','all']} labels={{12:'12 meses',24:'24 meses',all:'Desde 2023'}} onChange={setWindow}/></>:<Select label="Año estacional" value={year} choices={[...new Set(traffic.map(r=>r.month.slice(0,4)))].sort().reverse()} onChange={setYear}/>}<Download rows={tab==='dashboard'?scope:traffic.filter(r=>selected.includes(r.airport)&&r.month.startsWith(year))} name="trafico-aeropuertos.csv"/></div>
 {metric==='cargoKg'&&<p className="av-note">Carga: Aena mide mercancías; Gibraltar incluye también correo y mensajería. Se muestran kg con esa diferencia de cobertura.</p>}</>}
 {tab==='dashboard'&&(selected.length&&end?<>
 <div className="av-period"><h2>{formatMonth(end)}</h2><span>{selected.length} aeropuertos · mismo mes para todos</span></div>
 <DataComponent id="selection-summary" queryId="traffic" kind="metric" title={`${metricNames[metric]} de la selección`} sourceRows={compare} displayRows={[{Mes:end,Indicador:metricNames[metric],Actual:current,Anterior:prev,'Variación interanual (%)':delta(current,prev)}]}><div className="av-summary" data-reviewed-rows><div><strong>{formatCompact(current)}</strong><span>{metricNames[metric].toLowerCase()} · {formatNumber(current)}</span></div><div><b>{delta(current,prev)==null?'Sin base comparable':`${delta(current,prev)>0?'+':''}${delta(current,prev).toFixed(1).replace('.',',')} %`}</b><span>frente al mismo mes del año anterior</span></div><p>{metric==='passengers'?'Llegadas y salidas, no personas únicas. Un viaje entre dos aeropuertos seleccionados puede aparecer en ambos.':metric==='operations'?'Aterrizajes más despegues. Incluye actividad no comercial; no equivale al número de conexiones.':'Volumen publicado por cada fuente. Consulta la diferencia de cobertura de Gibraltar.'}</p></div></DataComponent>
 <SortableRegion id="airports:comparison" variant="canvas" columns={12} spacing="standard" rows={[{id:'rankings',items:['airport-volume','airport-growth']},{id:'history',items:['airport-history']}]}>
 <SortableItem id="airport-volume" label="Volumen por aeropuerto" kind="chart" span={6}><Plot id="airport-volume" title={`${metricNames[metric]} por aeropuerto`} type="horizontalBar" x="Aeropuerto" y={metricNames[metric]} rows={ranking} sourceRows={compare.filter(r=>r.month===end)} height={Math.max(270,selected.length*34)}/></SortableItem>
 <SortableItem id="airport-growth" label="Variación interanual" kind="chart" span={6}><Plot id="airport-growth" title="Variación interanual" type="horizontalBar" x="Aeropuerto" y="Variación interanual (%)" rows={ranking} sourceRows={compare} height={Math.max(270,selected.length*34)} description="(Valor del mes / mismo mes del año anterior − 1) × 100. Base ausente o cero: sin variación."/></SortableItem>
 <SortableItem id="airport-history" label="Evolución mensual" kind="chart" span={12}><Plot id="airport-history" title="Evolución mensual" y={indexed?'Índice (base 100)':metricNames[metric]} series="Aeropuerto" rows={trend} sourceRows={scope} height={340} headerControls={<Select label="Escala" value={indexed?'index':'absolute'} choices={['absolute','index']} labels={{absolute:'Volumen absoluto',index:'Índice · inicio = 100'}} onChange={v=>setIndexed(v==='index')}/>} description={indexed?'Valor mensual / primer mes del periodo × 100. Base cero o ausente: sin índice.':'Valores mensuales sin acumular. Huecos: datos ausentes, no ceros.'}/></SortableItem>
 </SortableRegion><details className="av-details"><summary>Consultar valores exactos del mes</summary><DataComponent id="month-table" queryId="traffic" kind="table" title="Detalle de la comparación" displayRows={ranking} sourceRows={compare}><DataTable rows={ranking} columns={Object.keys(ranking[0]).map(field=>({field,label:field}))} searchable={false}/></DataComponent></details>
 </>:<Empty>Selecciona al menos un aeropuerto con un periodo común.</Empty>)}
 {tab==='season'&&<Season {...{traffic,selected,metric,year,label,end}}/>}
 {tab==='detail'&&<Detail {...{queries,airports,detail,setDetail,label,name}}/>}
 {tab==='sources'&&<Sources {...{snapshot,queries,airports}}/>}
 <footer className="av-footer"><span>Estadísticas publicadas · comprobación diaria de las fuentes</span><a href="https://github.com/JoseHino/observatorio-aereo" target="_blank" rel="noreferrer">Código y actualizaciones ↗</a></footer></div>;
}
function Season({traffic,selected,metric,year,label,end}){
 const scoped=traffic.filter(r=>selected.includes(r.airport)&&r.month.startsWith(year)),complete=selected.filter(c=>scoped.filter(r=>r.airport===c&&r[metric]!=null).length===12);
 const shares=complete.flatMap(c=>{const rs=scoped.filter(r=>r.airport===c),total=rs.reduce((a,r)=>a+r[metric],0);return rs.map(r=>({Mes:monthNames[Number(r.month.slice(5))-1],Aeropuerto:label(c),'Peso en el año (%)':total>0?r[metric]/total*100:null}));});
 const cutoff=Number(end?.slice(5)??12),annual=annualRows(traffic,selected,cutoff,metric,label);
 return selected.length?<><Section id="season-heading" title="Cómo se distribuye la actividad durante el año" spacing="none"><Plot id="seasonal-profile" title="Peso de cada mes en el total anual" y="Peso en el año (%)" series="Aeropuerto" rows={shares} sourceRows={scoped.filter(r=>complete.includes(r.airport))} height={330} description="Valor de cada mes / suma de los 12 meses × 100. Solo años completos. Un total cero queda sin porcentaje."/>{complete.length<selected.length&&<p className="av-note">Sin año completo de {year}: {selected.filter(c=>!complete.includes(c)).map(label).join(', ')}. No se anualizan datos parciales.</p>}</Section><Section id="annual-heading" title={`Comparación anual · enero a ${monthNames[cutoff-1].toLowerCase()}`}><Plot id="annual-comparison" title={`${metricNames[metric]} en el mismo tramo de cada año`} type="bar" x="Año" y={metricNames[metric]} series="Aeropuerto" rows={annual} sourceRows={traffic.filter(r=>selected.includes(r.airport)&&Number(r.month.slice(5))<=cutoff)} height={330} description="Suma de los mismos meses de cada año. Un tramo incompleto queda sin dato."/></Section></>:<Empty>Selecciona al menos un aeropuerto.</Empty>;
}
function Detail({queries,airports,detail,setDetail,label,name}){
 const [chosen,setChosen]=useState('latest');const routes=queries.uk_routes.rows.filter(r=>r.airport===detail),countries=queries.countries.rows.filter(r=>r.airport===detail),mix=queries.mix.rows.filter(r=>r.airport===detail),core=queries.traffic.rows.filter(r=>r.airport===detail);
 const months=[...new Set(core.map(r=>r.month))].sort(),end=chosen==='latest'?months.at(-1):chosen,pick=rs=>rs.filter(r=>r.month<=end).map(r=>r.month).sort().at(-1),routeMonth=pick(routes),countryMonth=pick(countries),mixMonth=pick(mix);
 const cr=routes.filter(r=>r.month===routeMonth),co=countries.filter(r=>r.month===countryMonth),mx=mix.filter(r=>r.month===mixMonth);
 const routeBars=cr.map(r=>({'Aeropuerto británico':r.ukAirport,Pasajeros:r.passengers})).sort((a,b)=>b.Pasajeros-a.Pasajeros),countryBars=co.map(r=>({'País del vuelo':countriesES.of(r.country==='EL'?'GR':r.country==='UK'?'GB':r.country)??r.countryLabel,Pasajeros:r.passengers})).sort((a,b)=>b.Pasajeros-a.Pasajeros),mixRows=mx.map(r=>({Mercado:r.market==='NAT'?'Nacional':'Internacional',Pasajeros:r.passengers}));
 const from=shiftMonth(end,-11),ukHistory=routes.filter(r=>r.month>=from&&r.month<=end),ukTotals=Array.from({length:12},(_,i)=>{const m=shiftMonth(from,i),rs=ukHistory.filter(r=>r.month===m);return {Mes:m+'-01',Pasajeros:rs.length?rs.reduce((a,r)=>a+r.passengers,0):null};});
 const arr=core.filter(r=>r.month>=from&&r.month<=end).map(r=>({Mes:r.month+'-01',Llegadas:r.arrivals,Salidas:r.departures}));
 return <><div className="av-controls"><Select label="Aeropuerto" value={detail} choices={airports.map(a=>a.code)} labels={Object.fromEntries(airports.map(a=>[a.code,label(a.code)]))} onChange={setDetail}/><Select label="Consultar hasta" value={chosen} choices={['latest',...months.slice().reverse()]} labels={Object.fromEntries([['latest','Último mes disponible'],...months.map(m=>[m,formatMonth(m)])])} onChange={setChosen}/></div>
 <div className="av-detail-title"><b>{detail}</b><div><h2>{name(detail)}</h2><p>Desgloses con su propia cobertura y fecha de publicación.</p></div></div>
 <Section id="uk-heading" title="Conectividad con Reino Unido" spacing="none" columns={2}><Plot id="detail-uk-routes" queryId="uk_routes" title={`Pasajeros por ruta · ${formatMonth(routeMonth)}`} rows={topWithRest(routeBars,'Aeropuerto británico')} sourceRows={cr} type="horizontalBar" x="Aeropuerto británico" y="Pasajeros" height={360} description="CAA tabla 12.1. Ambos sentidos. Las 12 rutas de mayor volumen y el resto agrupado; los valores completos están en los datos y el CSV."/><Plot id="detail-uk-trend" queryId="uk_routes" title="Evolución del mercado británico" rows={ukTotals} sourceRows={ukHistory} y="Pasajeros" height={360}/></Section>
 {!routes.length&&<p className="av-note">Sin rutas británicas publicadas para este aeropuerto en el histórico cargado. Ausencia de registros no equivale a tráfico cero.</p>}
 <Section id="country-heading" title="Mercados europeos y tráfico nacional" columns={2}><Plot id="detail-countries" queryId="countries" title={`Países socios europeos · ${formatMonth(countryMonth)}`} rows={topWithRest(countryBars,'País del vuelo')} sourceRows={co} type="horizontalBar" x="País del vuelo" y="Pasajeros" height={360} description="Los 12 países con mayor volumen y el resto agrupado. Incluye España; no representa todos los destinos mundiales."/><Plot id="detail-mix" queryId="mix" title={`Nacional e internacional · ${formatMonth(mixMonth)}`} rows={mixRows} sourceRows={mx} type="horizontalBar" x="Mercado" y="Pasajeros" height={360}/></Section>
 <p className="av-note">Eurostat: países europeos declarantes, no todos los destinos mundiales ni nacionalidades. Sus periodos y definiciones pueden diferir de Aena y CAA; estas fuentes no se suman entre sí. {countries.length?'':'Sin desglose Eurostat para este aeropuerto.'}</p>
 {arr.some(r=>r.Llegadas!=null)&&<Section id="arrivals-heading" title="Llegadas y salidas"><EvidenceChart id="detail-arrivals" queryId="traffic" variant="card" title="Pasajeros de llegada y salida" rows={arr} sourceRows={core.filter(r=>r.month>=from&&r.month<=end)} spec={{type:'line',x:'Mes',y:'Llegadas',fields:['Llegadas','Salidas'],startAtZero:true,stackable:false}} height={300}/></Section>}
 <details className="av-details"><summary>Consultar y descargar las rutas del mes</summary><Download rows={cr} name={`rutas-${detail}-${routeMonth}.csv`}/><DataComponent id="routes-table" queryId="uk_routes" title="Rutas británicas" kind="table" sourceRows={cr} displayRows={routeBars}><DataTable rows={routeBars} columns={[{field:'Aeropuerto británico',label:'Aeropuerto británico'},{field:'Pasajeros',label:'Pasajeros'}]}/></DataComponent></details></>;
}
function Sources({snapshot,queries,airports}){
 const links=[['Aena · informes mensuales','https://www.aena.es/es/estadisticas/informes-mensuales.html'],['Gibraltar · estadísticas aeroportuarias','https://gibraltarairport.gi/about-us/air-traffic-statistics'],['Eurostat · países socios','https://ec.europa.eu/eurostat/databrowser/view/avia_paoac/default/table?lang=en'],['Eurostat · nacional/internacional','https://ec.europa.eu/eurostat/databrowser/view/avia_paoa/default/table?lang=en'],['CAA · estadísticas de aeropuertos','https://www.caa.co.uk/data-and-analysis/uk-aviation-market/airports/']];
 const coverage=airports.map(a=>{const last=q=>queries[q].rows.filter(r=>r.airport===a.code).map(r=>r.month).sort().at(-1)??'Sin datos';return {Aeropuerto:a.name,IATA:a.code,'Tráfico común':last('traffic'),'Países europeos':last('countries'),'Nacional/internacional':last('mix'),'Rutas Reino Unido':last('uk_routes')};});
 return <><Section id="coverage-heading" title="Qué se puede comparar" spacing="none"><DataComponent id="coverage-table" queryId="traffic" queryIds={Object.keys(queries)} title="Último mes disponible por aeropuerto y fuente" kind="table" displayRows={coverage} sourceRowsByQuery={Object.fromEntries(Object.entries(queries).map(([k,v])=>[k,v.rows]))}><DataTable rows={coverage} columns={Object.keys(coverage[0]).map(field=>({field,label:field}))} searchable={false}/></DataComponent></Section>
 <Section id="sources-heading" title="Fuentes originales"><div className="av-source-links">{links.map(([l,u])=><a key={u} href={u} target="_blank" rel="noreferrer">{l}<span>↗</span></a>)}</div></Section>
 <Section id="definitions-heading" title="Definiciones y límites"><div className="av-methods"><div><h3>Comparación mensual</h3><p>Se utiliza el último mes con datos de todos los aeropuertos seleccionados. El crecimiento se compara con el mismo mes del año anterior. Los datos ausentes se mantienen sin dato.</p><h3>Pasajeros y operaciones</h3><p>Los pasajeros son movimientos de llegada y salida, no viajeros únicos ni turistas. Las operaciones incluyen actividad no comercial. Pasajeros por operación no sería una medida de ocupación.</p></div><div><h3>Detalle con cobertura propia</h3><p>CAA cubre conexiones con Reino Unido. Eurostat distingue países europeos declarantes y tráfico nacional/internacional. Los países corresponden a los vuelos. El detalle completo de Aena por aerolínea y destino requiere registro y no está integrado.</p><h3>Actualización automática</h3><p>GitHub Actions comprueba las fuentes diariamente a las 07:20 UTC. Se publican con distintos retrasos. Si una fuente falla se conserva su histórico; si falla la validación no se sustituye la web publicada.</p></div></div></Section>
 <Section id="downloads-heading" title="Datos reutilizables"><div className="av-downloads">{Object.entries(queries).map(([id,q])=><div key={id}><b>{q.source.label}</b><span>{formatNumber(q.rows.length)} registros</span><Download rows={q.rows} name={`${id}.csv`}/></div>)}</div></Section>
 <p className="av-note">Última comprobación: {stamp(snapshot.refresh?.checkedAt??snapshot.generatedAt)}. {snapshot.refresh?.warnings?.length?`${snapshot.refresh.warnings.length} publicación(es) no disponibles en la última comprobación.`:'Sin incidencias en la última comprobación.'} <a href="https://github.com/JoseHino/observatorio-aereo/actions" target="_blank" rel="noreferrer">Ver ejecuciones ↗</a></p></>;
}
